//
//  StyleKit.h
//  CircleAnimation
//
//  Created by 能登 要 on 2015/05/06.
//  Copyright (c) 2015 Irimasu Densan Planning. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKit : NSObject

// Drawing Methods
+ (void)drawCircleWithFrame: (CGRect)frame circleColor: (UIColor*)circleColor endAngle: (CGFloat)endAngle interactiveFrame: (CGRect)interactiveFrame brushWidth: (CGFloat)brushWidth;

@end
